name: Build desktop apps
on:
  workflow_call:
    outputs:
      ARTIFACTS_NAME:
        description: "The name of artifact archive name"
        value: ${{ jobs.collect.outputs.ARTIFACTS_NAME }}
    inputs:
      BUILD_NUMBER:
        required: true
        type: string

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Java JDK
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build the project
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ inputs.BUILD_NUMBER }}
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: artifacts-windows
          path: instances/bsb/build/compose/binaries/main/msi/*
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Java JDK
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build the project
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ inputs.BUILD_NUMBER }}
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: artifacts-linux
          path: instances/bsb/build/compose/binaries/main/deb/*
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Java JDK
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build the project
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ inputs.BUILD_NUMBER }}
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: artifacts-macos
          path: instances/bsb/build/compose/binaries/main/dmg/*
  collect:
    name: Collect all artifacts to one archive
    runs-on: ubuntu-latest
    needs: [ build-windows, build-linux, build-macos ]
    outputs:
      ARTIFACTS_NAME: ${{ steps.echo_output.outputs.ARTIFACTS_NAME }}
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        id: download
        with:
          path: download
          pattern: artifacts-*
          merge-multiple: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: artifacts-output
          path: ${{steps.download.outputs.download-path}}
      - id: echo_output
        run: echo "ARTIFACTS_NAME=artifacts-output" >> $GITHUB_OUTPUT
