name: Create build number
on:
  workflow_call:
    secrets:
      SIGNING_KEY:
        required: true
      KEY_ALIAS:
        required: true
      KEY_STORE_PASSWORD:
        required: true
      KEY_ALIAS_PASSWORD:
        required: true
    outputs:
      ARTIFACTS_OUTPUT_PATH:
        description: "Uploaded artifacts path"
        value: ${{ jobs.build_upload_artifacts.outputs.ARTIFACTS_OUTPUT_PATH }}
    inputs:
        BUILD_NUMBER:
          required: true
          type: string
        # :instances:app
        # :instances:wear 
        MODULE_PATH:
            required: true
            type: string
        # instances/bsb
        DIR_PATH:
          required: true
          type: string
        # android-dev
        # wearos-dev
        IDENTIFIER:
          required: true
          type: string
        FLAVOR_TYPE:
            required: true
            type: string
          

jobs:
  build_upload_artifacts:
    name: Build AAB and APK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ext: "apk"
            release_directory: "${{ inputs.DIR_PATH }}/build/outputs/apk/release"
            task: ./gradlew ${{ inputs.MODULE_PATH }}:assembleRelease
          - ext: "aab"
            release_directory: "${{ inputs.DIR_PATH }}/build/outputs/bundle/release"
            task: ./gradlew ${{ inputs.MODULE_PATH }}:bundleRelease

    env:
        ORG_GRADLE_PROJECT_current_flavor_type: ${{ inputs.FLAVOR_TYPE }}
    outputs:
        ARTIFACTS_OUTPUT_PATH: ${{ steps.artifacts_copy.outputs.path }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build release
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ inputs.BUILD_NUMBER }}
        run: ${{ matrix.task }}
      # ${{ steps.sign.outputs.signedReleaseFile }}
      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407 # v1
        with:
          releaseDirectory: ${{ matrix.release_directory }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      # ${{ steps.artifacts_copy.outputs.path }}
      - name: Copy artifacts
        id: artifacts_copy
        run: |
          mkdir artifacts
          cp ${{ steps.sign.outputs.signedReleaseFile }} artifacts/busystatusbar-${{ inputs.IDENTIFIER }}.${{ matrix.ext }}
          cp ${{ inputs.DIR_PATH }}/outputs/mapping/release/mapping.txt artifacts/mapping-${{ inputs.IDENTIFIER }}.txt
          echo "path=artifacts/" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: artifacts
          path: ${{ steps.artifacts_copy.outputs.path }}