name: Create build number
on:
  workflow_call:
    secrets:
      SIGNING_KEY:
        required: true
      KEY_ALIAS:
        required: true
      KEY_STORE_PASSWORD:
        required: true
      KEY_ALIAS_PASSWORD:
        required: true
    outputs:
      ARTIFACTS_NAME:
        description: "Name of uploaded artifacts"
        value: ${{ jobs.build_upload_artifacts.outputs.ARTIFACTS_NAME }}
    inputs:
      BUILD_NUMBER:
        required: true
        type: string
      MAJOR_VERSION:
        required: true
        type: string
      # :instances:app
      # :instances:wear
      MODULE_PATH:
        required: true
        type: string
      # instances/bsb
      DIR_PATH:
        required: true
        type: string
      # android-dev
      # wearos-dev
      IDENTIFIER:
        required: true
        type: string
      FLAVOR_TYPE:
        required: true
        type: string


jobs:
  build_upload_artifacts:
    name: Build AAB and APK
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_current_flavor_type: ${{ inputs.FLAVOR_TYPE }}
    outputs:
      ARTIFACTS_NAME: artifacts-${{ inputs.IDENTIFIER }}-${{ inputs.FLAVOR_TYPE }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Copy artifacts
        id: artifacts_copy
        run: |
          mkdir artifacts
          echo HelloWorld >> artifacts/busystatusbar-${{ inputs.IDENTIFIER }}-${{ inputs.MAJOR_VERSION }}.${{ inputs.BUILD_NUMBER }}.aab
          echo HelloWorld >> artifacts/busystatusbar-${{ inputs.IDENTIFIER }}-${{ inputs.MAJOR_VERSION }}.${{ inputs.BUILD_NUMBER }}.apk
          echo HelloWorld >> artifacts/mapping-${{ inputs.IDENTIFIER }}.txt
          echo "path=artifacts/" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: artifacts-${{ inputs.IDENTIFIER }}-${{ inputs.FLAVOR_TYPE }}
          path: ${{ steps.artifacts_copy.outputs.path }}