name: Assemble android-based module
on:
  workflow_call:
    secrets:
      SIGNING_KEY:
        required: true
      KEY_ALIAS:
        required: true
      KEY_STORE_PASSWORD:
        required: true
      KEY_ALIAS_PASSWORD:
        required: true
    outputs:
      ARTIFACTS_NAME:
        description: "Name of uploaded artifacts"
        value: ${{ jobs.build_upload_artifacts.outputs.ARTIFACTS_NAME }}
    inputs:
      BUILD_NUMBER:
        required: true
        type: string
      MAJOR_VERSION:
        required: true
        type: string
      # :instances:app
      # :instances:wear
      MODULE_PATH:
        required: true
        type: string
      # instances/bsb
      DIR_PATH:
        required: true
        type: string
      # android-dev
      # wearos-dev
      IDENTIFIER:
        required: true
        type: string
      FLAVOR_TYPE:
        required: true
        type: string

env:
  ARTIFACTS_FOLDER_PATH: artifacts
  ARTIFACT_NAME: artifacts-${{ inputs.IDENTIFIER }}-${{ inputs.FLAVOR_TYPE }}

jobs:
  build_upload_artifacts:
    name: Build AAB and APK ${{ inputs.FLAVOR_TYPE }}-${{ inputs.identifier }}
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_current_flavor_type: ${{ inputs.FLAVOR_TYPE }}
    outputs:
      ARTIFACTS_NAME: ${{ env.ARTIFACT_NAME }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build release
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ inputs.BUILD_NUMBER }}
        run: ./gradlew ${{ inputs.MODULE_PATH }}:assembleRelease ${{ inputs.MODULE_PATH }}:bundleRelease
      # ${{ steps.sign_aab.outputs.signedReleaseFile }}
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407 # v1
        with:
          releaseDirectory: ${{ inputs.DIR_PATH }}/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      # ${{ steps.sign_apk.outputs.signedReleaseFile }}
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407 # v1
        with:
          releaseDirectory: ${{ inputs.DIR_PATH }}/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      # ${{ steps.artifacts_copy.outputs.path }}
      - name: Copy artifacts
        run: |
          mkdir ${{ env.ARTIFACTS_FOLDER_PATH }}
          cp ${{ steps.sign_apk.outputs.signedReleaseFile }} ${{ env.ARTIFACTS_FOLDER_PATH }}/busystatusbar-${{ inputs.IDENTIFIER }}-${{ inputs.MAJOR_VERSION }}.${{ inputs.BUILD_NUMBER }}.aab
          cp ${{ steps.sign_aab.outputs.signedReleaseFile }} ${{ env.ARTIFACTS_FOLDER_PATH }}/busystatusbar-${{ inputs.IDENTIFIER }}-${{ inputs.MAJOR_VERSION }}.${{ inputs.BUILD_NUMBER }}.apk
          cp ${{ inputs.DIR_PATH }}/build/outputs/mapping/release/mapping.txt ${{ env.ARTIFACTS_FOLDER_PATH }}/mapping-${{ inputs.IDENTIFIER }}.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACTS_FOLDER_PATH }}