name: Build desktop apps
on:
  workflow_call:
    outputs:
      ARTIFACTS_NAME:
        description: "The name of artifact archive name"
        value: ${{ jobs.collect.outputs.ARTIFACTS_NAME }}
    inputs:
      BUILD_NUMBER:
        required: true
        type: string

env:
  ARTIFACT_NAME: artifacts-output

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Java JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build the project
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ inputs.BUILD_NUMBER }}
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: artifacts-windows
          path: instances/bsb/build/compose/binaries/main/msi/*
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Java JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build the project
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ inputs.BUILD_NUMBER }}
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: artifacts-linux
          path: instances/bsb/build/compose/binaries/main/deb/*
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Java JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build the project
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ inputs.BUILD_NUMBER }}
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: artifacts-macos
          path: instances/bsb/build/compose/binaries/main/dmg/*
  collect:
    name: Collect all artifacts to one archive
    runs-on: ubuntu-latest
    needs: [ build-windows, build-linux, build-macos ]
    outputs:
      ARTIFACTS_NAME: ${{ env.ARTIFACT_NAME }}
    steps:
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
        id: download
        with:
          path: download
          pattern: artifacts-*
          merge-multiple: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{steps.download.outputs.download-path}}
