name: Pull Request CI

on:
  pull_request:
  merge_group:

# Concurrency strategy:
#   github.workflow: distinguish this workflow from others
#   github.event_name: distinguish `push` event from `pull_request` and 'merge_group' event
#   github.ref_name: distinguish branch
#   github.repository: distinguish owner+repository
#
# Reference:
#   https://docs.github.com/en/actions/using-jobs/using-concurrency
#   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{github.ref_name}}-${{github.repository}}
  cancel-in-progress: true


jobs:
  info:
    name: "Display concurrency info"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.workflow=${{ github.workflow }}"
          echo "github.event_name=${{ github.event_name }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.repository=${{ github.repository }}"
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ "testDebugUnitTest", "desktopTest" ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Test ${{ matrix.target }}"
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: ${{ matrix.target }}
  detekt:
    name: "Check project by linters"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ "detektMetadataCommonMain", "lint" ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Lint by ${{ matrix.target }}"
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: ${{ matrix.target }}
  build:
    name: "Test build for Android/Desktop"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ "assembleDebug", "packageDistributionForCurrentOS" ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Build by ${{ matrix.target }}"
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: ${{ matrix.target }}