name: Build and publish

on:
  push:
    branches:
      - 'main'

env:
  FLAVOR_TYPE: PROD
  GP_TRACK: internal

jobs:
  # ${{ needs.build_number.outputs.BUILD_NUMBER }}
  build_number:
    name: "Create build number"
    uses: ./.github/workflows/call-build-number.yml

  # ${{ needs.assemble_android.outputs.ARTIFACTS_OUTPUT_PATH }}
  # ${{ needs.assemble_android.outputs.ARTIFACTS_NAME }}
  assemble_android:
    name: "Assemble Android-${{ env.FLAVOR_TYPE }}"
    needs: [ build_number ]
    uses: ./.github/workflows/call-assemble-android.yml
    secrets:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
    with:
      BUILD_NUMBER: ${{ needs.build_number.outputs.BUILD_NUMBER }}
      MAJOR_VERSION: ${{ needs.build_number.outputs.MAJOR_VERSION }}
      MODULE_PATH: ":instances:bsb"
      DIR_PATH: "instances/bsb"
      IDENTIFIER: "android-${{ env.FLAVOR_TYPE }}"
      FLAVOR_TYPE: ${{ env.FLAVOR_TYPE }}

  # ${{ needs.assemble_wearos.outputs.ARTIFACTS_OUTPUT_PATH }}
  # ${{ needs.assemble_wearos.outputs.ARTIFACTS_NAME }}
  assemble_wearos:
    name: "Assemble WearOS-${{ env.FLAVOR_TYPE }}"
    needs: [ build_number ]
    uses: ./.github/workflows/call-assemble-android.yml
    secrets:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
    with:
      BUILD_NUMBER: ${{ needs.build_number.outputs.BUILD_NUMBER }}
      MAJOR_VERSION: ${{ needs.build_number.outputs.MAJOR_VERSION }}
      MODULE_PATH: ":instances:bsb-wear"
      DIR_PATH: "instances/bsb-wear"
      IDENTIFIER: "wear-${{ env.FLAVOR_TYPE }}"
      FLAVOR_TYPE: ${{ env.FLAVOR_TYPE }}

  # ${{ needs.build_desktop.outputs.ARTIFACTS_NAME }}
  build_desktop:
    name: "Build desktop app"
    needs: [ build_number ]
    uses: ./.github/workflows/call-desktop-build.yml
    with:
      BUILD_NUMBER: ${{ needs.build_number.outputs.BUILD_NUMBER }}

  upload_playstore_android:
    name: "Upload PlayStore Android-${{ env.FLAVOR_TYPE }}"
    needs: [ build_number, assemble_android ]
    uses: ./.github/workflows/call-upload-playstore.yml
    secrets:
      GOOGLE_PLAY_PUBLISHER_JSON: ${{ secrets.GOOGLE_PLAY_PUBLISHER_JSON }}
    with:
      ARTIFACT_NAME: ${{ needs.assemble_android.outputs.ARTIFACTS_NAME }}
      IDENTIFIER: "android-${{ env.FLAVOR_TYPE }}"
      FLAVOR_TYPE: ${{ env.FLAVOR_TYPE }}
      TRACK: ${{ env.GP_TRACK }}
  
  upload_playstore_wear:
    name: "Upload PlayStore WearOS-${{ env.FLAVOR_TYPE }}"
    needs: [ build_number, assemble_wearos ]
    uses: ./.github/workflows/call-upload-playstore.yml
    secrets:
      GOOGLE_PLAY_PUBLISHER_JSON: ${{ secrets.GOOGLE_PLAY_PUBLISHER_JSON }}
    with:
      ARTIFACT_NAME: ${{ needs.assemble_wearos.outputs.ARTIFACTS_NAME }}
      IDENTIFIER: "android-${{ env.FLAVOR_TYPE }}"
      FLAVOR_TYPE: ${{ env.FLAVOR_TYPE }}
      TRACK: ${{ env.GP_TRACK }}
  
  upload_to_github:
    name: Upload to Github Releases
    runs-on: ubuntu-latest
    needs: [ assemble_android, assemble_wearos, build_desktop, build_number ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Install zip
        uses: montudor/action-zip@a8e75c9faefcd80fac3baf53ef40b9b119d5b702 # v1

      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
        id: download_desktop
        with:
          name: ${{ needs.build_desktop.outputs.ARTIFACTS_NAME }}
          path: download/artifacts-desktop

      # ${{ steps.download_android_prod.outputs.download-path }}
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
        id: download_android_prod
        with:
          name: ${{ needs.assemble_android.outputs.ARTIFACTS_NAME }}
          path: artifacts/download_android_prod

      # ${{ steps.download_wear_prod.outputs.download-path }}
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
        id: download_wear_prod
        with:
          name: ${{ needs.assemble_wearos.outputs.ARTIFACTS_NAME }}
          path: artifacts/download_wear_prod

      - name: Prepare mapping
        id: mappings
        run: |
          mkdir mappings
          mv "${{ steps.download_android_prod.outputs.download-path }}/mapping-android.txt" mappings/
          mv "${{ steps.download_wear_prod.outputs.download-path }}/mapping-wear.txt" mappings/
          zip -qq -r mappings.zip mappings
          echo "archive=mappings.zip" >> $GITHUB_OUTPUT
      - name: Prepare other builds
        id: other
        run: |
          mkdir other
          mv ${{ steps.download_android_prod.outputs.download-path }}/*.aab other/
          mv ${{ steps.download_wear_prod.outputs.download-path }}/*.aab other/
          zip -qq -r other.zip other
          echo "archive=other.zip" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.mappings.outputs.archive }}
            ${{ steps.other.outputs.archive }}
            ${{ steps.download_android_prod.outputs.download-path }}/*.apk
            ${{ steps.download_wear_prod.outputs.download-path }}/*.apk
            ${{steps.download_desktop.outputs.download-path}}/*
          tag_name: ${{ needs.build_number.outputs.MAJOR_VERSION }}.${{ needs.build_number.outputs.BUILD_NUMBER }}
          name: Busy App ${{ needs.build_number.outputs.MAJOR_VERSION }}.${{ needs.build_number.outputs.BUILD_NUMBER }}
          draft: false
          body: |
            Web version: [https://busy-app.github.io/Android/](https://busy-app.github.io/Android/)
            
            Doesn't work on Safari until this [PR by Apple](https://github.com/WebKit/WebKit/pull/31854) is released
            
