name: Build and publish

on:
  push:
    branches:
      - 'main'

jobs:
  # ${{ needs.build_number.outputs.BUILD_NUMBER }}
  build_number:
    name: "Create build number"
    uses: ./.github/workflows/call-build-number.yml
    
  # ${{ needs.build_android_flavor_dev.outputs.ARTIFACTS_OUTPUT_PATH }}
  build_android_flavor_dev:
    name: "Build android-dev"
    needs: [ build_number ]
    uses: ./.github/workflows/call-assemble-android.yml
    secrets:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
    with:
      BUILD_NUMBER: ${{ needs.build_number.outputs.BUILD_NUMBER }}
      MAJOR_VERSION: ${{ needs.build_number.outputs.MAJOR_VERSION }}
      MODULE_PATH: ":instances:bsb-test"
      DIR_PATH: "instances/bsb-test"
      IDENTIFIER: "android"
      FLAVOR_TYPE: "DEV"

  # ${{ needs.build_desktop.outputs.ARTIFACTS_NAME }}
  #build_desktop:
  #  name: "Build desktop app"
  #  needs: [ build_number ]
  #  uses: ./.github/workflows/call-desktop-build.yml
  #  with:
  #    BUILD_NUMBER: ${{ needs.build_number.outputs.BUILD_NUMBER }}

  upload_to_github:
    name: Upload to Github Releases
    runs-on: ubuntu-latest
    needs: [ build_android_flavor_dev, build_number ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Install zip
        uses: montudor/action-zip@a8e75c9faefcd80fac3baf53ef40b9b119d5b702 # v1


#      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
#        id: download-desktop
#        with:
#          name: ${{ needs.build_desktop.outputs.ARTIFACTS_NAME }}
#          path: download/artifacts-desktop

      # ${{ steps.download_android_dev.outputs.download-path }}
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
        id: download_android_dev
        with:
          name: ${{ needs.build_android_flavor_dev.outputs.ARTIFACTS_NAME }}
          path: ${{ steps.download.outputs.download-path }}
      - name: Prepare mapping
        id: mappings
        run: |
          mkdir mappings
          mv "${{ steps.download_android_dev.outputs.download-path }}/mapping-android.txt" mappings/
          zip -qq -r mappings.zip mappings
          echo "archive=mappings.zip" >> $GITHUB_OUTPUT
      - name: Prepare other builds
        id: other
        run: |
          mkdir other
          mv ${{ steps.download_android_dev.outputs.download-path }}/*.aab other/
          zip -qq -r other.zip other
          echo "archive=other.zip" >> $GITHUB_OUTPUT
      - name: 'Set variables'
        id: vars
        run: |
          export $(cat .github/workflows/version.env | xargs)
          echo "minor_version=${{ needs.build_number.outputs.number }}" >> $GITHUB_OUTPUT
      - name: Create internal Release
        id: create_internal_release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.mappings.outputs.archive }}
            ${{ steps.other.outputs.archive }}
            ./artifacts/android/*.apk
            ${{steps.download-desktop.outputs.download-path}}/*
          tag_name: ${{ needs.build_number.outputs.MAJOR_VERSION }}.${{ needs.build_number.outputs.BUILD_NUMBER }}
          name: Busy App ${{ needs.build_number.outputs.MAJOR_VERSION }}.${{ needs.build_number.outputs.BUILD_NUMBER }}
          draft: false
          body: |
            Web version: [https://busy-app.github.io/Android/](https://busy-app.github.io/Android/)
            
            Doesn't work on Safari until this [PR by Apple](https://github.com/WebKit/WebKit/pull/31854) is released
            
